### ISSUE TITLE
Can't change stash overlay after accidently maximizing it

### ISSUE THREAD

**Issue by Hillgrove** [ChaosRecipeEnhancer/EnhancePoEApp#246]
title...

accidently dragged and dropped the stash overlay to the top of the screen, maximizing it. Now I can't make it smaller and I can't move it either.

**Comment by DevConFox** [comment]
Hi @Hillgrove 
Check you task bar after you toggled the stash overlay on. You should find one instance window for the actual overlay.

(for reference see attached screenshot)
1. Hover over the window preview for the overlay
2. right-click it
3. choose 'Restore' (first option from the top)
 
This should reset the size to your previous settings.

![image](https://user-images.githubusercontent.com/93077838/138612286-ee9f9eb6-bae3-4f51-889b-c07d5ac233df.png)

Make sure not to accendentially choose 'Close' (bottom last option). This will cause the app to crash, if you try to toggle the overlay. :D

Cheers!

**Comment by Hillgrove** [comment]
thanks for the support.. I ended up closing the app, and when i booted it up again, the window had slides a bit so I could re-size it and move it. :)
