### ISSUE TITLE
Q: Does tool work with private leagues?

### ISSUE THREAD

**Issue by zakaluka** [ChaosRecipeEnhancer/EnhancePoEApp#249]
Hi,

This is a great tool, but I am wondering if it works with private leagues.  If it does, what is the name expected in the "league" field?  I've tried everything I can think of, but it just keep saying "Bad Request".  Is there an API / call I can run to get the league name and put it into that field?

**Comment by justanotherbody** [comment]
This works for me in a private league as of 3.16 (the only time i've tried)

Go to: https://www.pathofexile.com/character-window/get-characters?accountName=YOUR_ACCOUNT_HERE

**you must be logged in to pathofexile.com** for this to work. just like the trade site doesn't show your private league unless you're logged in

Find your character and pull the league out. E.g., if it says `"league":"Standard"` then copy paste "Standard" in w/ no quotes.

Don't mess with the parenthesis or anything - copy paste the entire part between the double quotes.

**Comment by zakaluka** [comment]
That is perfect, thank you so much!
