### ISSUE TITLE
Can't fetch my loot filter

### ISSUE THREAD

**Issue by jnuey** [ChaosRecipeEnhancer/EnhancePoEApp#250]
When I got to select my filter, all I get is a blank screen. I've tried to get WIndows to show all files with no success.

**Comment by HiMarioLopez** [comment]
Howdy, we just released an updated version of the app (v1.3.0 via #268)

Is your issue still present after the update, or can we close this out?

**Comment by HiMarioLopez** [comment]
Closing as we've since released a few fixes to the filter features, as well as sunsetting online filter manipulation (which may or may not have been causing this bug). If you have any other issues with our new v1.4.0 release please open a new issue. Thanks!
