### ISSUE TITLE
Lootfilter Manipulation doesn't work

### ISSUE THREAD

**Issue by dejrons** [ChaosRecipeEnhancer/EnhancePoEApp#282]
I tried both downloaded filter and synchronised, reinstalled chaos recipe enhancer, pc reset. Nothing helps.

**Comment by HiMarioLopez** [comment]
Online or offline filters?

**Comment by HiMarioLopez** [comment]
Closing as we've since released a few fixes to the filter features, as well as sunsetting online filter manipulation (which may or may not have been causing this bug). If you have any other issues with our new v1.4.0 release please open a new issue. Thanks!
