### ISSUE TITLE
"Reload Filter" taking 10 seconds ever since v1.4.1.0

### ISSUE THREAD

**Issue by starfishbzdf** [ChaosRecipeEnhancer/EnhancePoEApp#310]
I've used the tool since February 10th, It used to work instantly in previous versions.
Youtube video showcasing the issue: https://youtu.be/S4d52LEWfMw
~~Note that the game goes out of focus for the whole period of reloading~~

Filter used is unmodified NS semi-strict saved locally on the machine: D:\Documents\My Games\Path of Exile\chaosrecipeenhancer.filter
OS is Windows 10 Pro 20H2 Version 10.0.19042 Build 19042
PC ain't weak either, i7-9700k, 32GB of ram, GTX 1070.

CRE settings: 
![image](https://user-images.githubusercontent.com/50381850/154717674-616ebe44-595b-4561-a9d1-bdf4a7dbf587.png)
![image](https://user-images.githubusercontent.com/50381850/154717716-fef17537-4936-47f4-ac86-80726305a92a.png)
![image](https://user-images.githubusercontent.com/50381850/154717750-2ab6a35a-ef59-45ee-922c-6635b080514f.png)

If there's anything else you need I'm willing to provide it.

**Comment by HiMarioLopez** [comment]
Thanks for the video! Based on your WQHD I'm assuming you're not running on a toaster, so I can't blame your hardware 😋

I'll be looking at these to see what we can optimize/fix, as there were some changes made to the filter reloading to fix some other bugs. This is related to those recent code changes, more likely than not.
