### ISSUE TITLE
[Bug] [General] Reloading filter pastes previous clipboard content; filter reload command is not properly being added to the user clipboard 

### ISSUE THREAD

**Issue by nightstalk3rxx** [ChaosRecipeEnhancer/EnhancePoEApp#379]
1/2 times when you press the reload filter button on the overlay the Program will paste whatever you have copied into the chat and send it, im not sure why but keep happening.
![Screenshot 2022-05-17 143445](https://user-images.githubusercontent.com/100140498/168811978-27296ad0-29d3-4f85-abcb-6ae85d8a1e43.png)

**Comment by HiMarioLopez** [comment]
Just want to validate you're running on v1.5.4, is that correct?

**Comment by nightstalk3rxx** [comment]
> Just want to validate you're running on v1.5.4, is that correct?

Correct

**Comment by HiMarioLopez** [comment]
Gotcha. I'll keep this one as the catch-all for any reports of the same issue (We've hade a few!)

https://github.com/kosace/EnhancePoEApp/issues/354#issuecomment-1127222015

**Comment by herofromhyrule** [comment]
This is still happening in version 1.6.0.2. Reloading the filter is sometimes putting my clipboard text into chat, but more commonly it seems to paste the filter update text (the edits being made to the item filter) into chat. I'm seeing it happen to other people in Global chat too.

**Comment by herofromhyrule** [comment]
Attaching image to show an example

![image](https://user-images.githubusercontent.com/61358514/185810549-67442200-3139-4b92-886b-b2148573795e.png)

**Comment by robertsimmons** [comment]
Happening to me much more than normal. Seeing it happen to guildies and stuff pretty often too (well, I did when they were playing, heh).

**Comment by HiMarioLopez** [comment]
What operating system are you guys on?

**Comment by robertsimmons** [comment]
Windows 11. A machine that's only a couple of months old, and is a powerful beast, TBH.

**Comment by herofromhyrule** [comment]
Windows 10 21H2

**Comment by Dogtron3030** [comment]
posting to say this is happening to me too. Windows 10. i've been trying to puzzle out what causes it but im not having much luck.

**Comment by Dominik-O22** [comment]
experiencing the same issue as well also on Windows 10 21H2

**Comment by 0xD21F** [comment]
This is a serious security issue, you're getting people pasting their clipboard into global/local chat. This could potentially include all sorts of privileged information (passwords, for example). This feature should be disabled IMMEDIATELY until fixed.

**Comment by 0xD21F** [comment]
I've made a [pull request](https://github.com/ChaosRecipeEnhancer/EnhancePoEApp/pull/432) that mitigates this issue. There may be a better solution, but for the time being something should be done to prevent this from occurring.

**Comment by HiMarioLopez** [comment]
Resolved with #432 

Appreciate your contribution, @drifio !
